# Generated by Django 5.2.3 on 2025-06-20 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1999, message='Year must be between 1999 and 2030!'), django.core.validators.MaxValueValidator(2030, message='Year must be between 1999 and 2030!')]),
        ),
    ]
